

// Objects
// const fullName = "Hello";

// const obj = {
//     name:"Abdullah",
//     classs:"Web",
//     age:20
// }

// delete obj.age;

// console.log(obj)


// Object Destructure
// const {name , classs , age} = obj;

// obj.name
// obj
// obj.Hell="Afzal";
// obj.classs = "Design";

// console.log(name)

// for (const prop in obj){
//         // console.log(prop)
//         const newObj ={[obj[prop]]:prop};
//         console.log(newObj)
// }


// [hello.name]
// const heading = document.getElementById("heading");
// // const inp = document.getElementById("inp").value;
// // console.log(inp);
// const span = document.getElementsByClassName("span")[1];
// span.setAttribute("id" ,"abc" );
// span.removeAttribute("id");
// const heading2 = document.getElementsByTagName("span");



const heading = document.querySelectorAll("span")[2];
heading.innerText = 'Shoib'



console.log(heading)